### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 1 : ndarray, np.array(iterable)
- 행열의 생성 2 : ones, zeros
- 행열 데이터 선택 : array[x, y, z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range : 결과가 ndarray

### quiz 
- 100 ~ 130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터

```
datas = np.random.randint(100, 130, size=(8, 8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()

In [0]:
datas = np.random.randint(100, 130, size=(8, 8))
datas

array([[114, 120, 117, 114, 116, 120, 104, 107],
       [123, 118, 104, 122, 101, 119, 110, 108],
       [107, 102, 125, 116, 101, 100, 120, 110],
       [112, 120, 107, 119, 122, 101, 127, 127],
       [108, 109, 111, 118, 109, 117, 113, 124],
       [111, 128, 102, 124, 120, 103, 121, 103],
       [105, 117, 102, 112, 102, 123, 114, 116],
       [113, 122, 129, 116, 105, 112, 113, 122]])

In [0]:
data1 = np.array([1,2,3]) 
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [0]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [0]:
# 데이터의 타입을 str으로 변환
datas.dtype

dtype('int64')

In [0]:
result = datas.astype("str")
result

array([['114', '120', '117', '114', '116', '120', '104', '107'],
       ['123', '118', '104', '122', '101', '119', '110', '108'],
       ['107', '102', '125', '116', '101', '100', '120', '110'],
       ['112', '120', '107', '119', '122', '101', '127', '127'],
       ['108', '109', '111', '118', '109', '117', '113', '124'],
       ['111', '128', '102', '124', '120', '103', '121', '103'],
       ['105', '117', '102', '112', '102', '123', '114', '116'],
       ['113', '122', '129', '116', '105', '112', '113', '122']],
      dtype='<U21')

In [0]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [0]:
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"

In [0]:
result

array([['fiz', 'fbz', 'fiz', 'fiz', '116', 'fbz', '104', '107'],
       ['fiz', '118', '104', '122', '101', '119', 'buz', 'fiz'],
       ['107', 'fiz', 'buz', '116', '101', 'buz', 'fbz', 'buz'],
       ['112', 'fbz', '107', '119', '122', '101', '127', '127'],
       ['fiz', '109', 'fiz', '118', '109', 'fiz', '113', '124'],
       ['fiz', '128', 'fiz', '124', 'fbz', '103', '121', '103'],
       ['fbz', 'fiz', 'fiz', '112', 'fiz', 'fiz', 'fiz', '116'],
       ['113', '122', 'fiz', '116', 'fbz', '112', '113', '122']],
      dtype='<U21')

### Quiz
- 1 ~ 20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수
```
np.min(ndarray), np.max(ndarray)
```

In [0]:
datas = np.random.randint(1, 20, (5, 5))
datas

array([[ 4, 10, 17,  2,  4],
       [ 8, 13, 16, 10, 18],
       [ 3,  1,  6,  7,  4],
       [ 9, 17,  5, 18,  2],
       [15, 17, 13, 11,  3]])

In [0]:
min_num, max_num = np.min(datas), np.max(datas)
min_num, max_num

(1, 18)

In [0]:
idx_min = datas == min_num
idx_max = datas == max_num

In [0]:
result = datas.astype("str")
result

array([['4', '10', '17', '2', '4'],
       ['8', '13', '16', '10', '18'],
       ['3', '1', '6', '7', '4'],
       ['9', '17', '5', '18', '2'],
       ['15', '17', '13', '11', '3']], dtype='<U21')

In [0]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"

In [0]:
result

array([['4', '10', '17', '2', '4'],
       ['8', '13', '16', '10', 'MAX'],
       ['3', 'MIN', '6', '7', '4'],
       ['9', '17', '5', 'MAX', '2'],
       ['15', '17', '13', '11', '3']], dtype='<U21')

In [0]:
data1 = np.random.randint(0, 10, size=(10000,10000))

In [0]:
idx_3 = data1 % 3 == 0

In [0]:
result = data1.astype("str")

In [0]:
result[idx_3] = "fiz"

In [0]:
result

array([['8', '4', '5', ..., '2', '8', '8'],
       ['5', '4', '4', ..., '4', 'fiz', '8'],
       ['fiz', 'fiz', '1', ..., 'fiz', '8', 'fiz'],
       ...,
       ['fiz', 'fiz', 'fiz', ..., '5', 'fiz', '8'],
       ['8', 'fiz', '2', ..., '1', '4', '5'],
       ['4', '2', '2', ..., '2', 'fiz', 'fiz']], dtype='<U21')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [0]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [0]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [0]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [0]:
age_30 = 100000
age_60 = 1000000

In [0]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [0]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 난수를 발생
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어 줍니다.
- choice : 특정 확률로 데이터를 선택

In [0]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [0]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [0]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [0]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[2, 8, 9, 3],
       [9, 8, 2, 7],
       [9, 6, 4, 1]])

In [0]:
np.random.shuffle(r)
r

array([[9, 6, 4, 1],
       [9, 8, 2, 7],
       [2, 8, 9, 3]])

In [0]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([4, 3, 2, 4, 2, 4, 4, 3, 4, 4])

In [0]:
# unique
numbers, counts = np.unique(r, return_counts=True) 
print(numbers)
print(counts)

[1 2 3 4 6 7 8 9]
[1 2 1 1 1 1 2 3]


### 3. 행렬 데이터의 결합
- concatenate

In [0]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [0]:
# 세로 결합
na1

array([[3, 0, 0],
       [5, 7, 5]])

In [0]:
na2

array([[0, 8],
       [6, 5],
       [1, 7]])

In [0]:
na3

array([[4, 3, 6],
       [1, 4, 0],
       [8, 5, 4]])

In [0]:
# 세로 결합
np.concatenate((na1, na3))

array([[3, 0, 0],
       [5, 7, 5],
       [4, 3, 6],
       [1, 4, 0],
       [8, 5, 4]])

In [0]:
# 가로 결합
np.concatenate((na2, na3), axis=1)

array([[0, 8, 4, 3, 6],
       [6, 5, 1, 4, 0],
       [1, 7, 8, 5, 4]])

In [0]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [0]:
# split, var, std, mean ...