In [2]:
datas = np.random.randint(100,130,size=(8,8))
datas.astype(str)

array([['128', '127', '106', '111', '102', '110', '103', '109'],
       ['107', '113', '126', '110', '113', '125', '123', '112'],
       ['118', '105', '123', '123', '115', '104', '129', '102'],
       ['101', '127', '109', '111', '110', '115', '129', '124'],
       ['113', '107', '109', '108', '106', '117', '114', '112'],
       ['123', '129', '105', '109', '113', '102', '100', '117'],
       ['104', '111', '106', '106', '117', '122', '115', '114'],
       ['116', '114', '100', '117', '112', '110', '108', '129']],
      dtype='<U21')

In [ ]:
datas[data]

In [1]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [2]:
array2= np.array(
    [[1,2,3],
    [4,5,6]]
)
array2,array2.ndim,array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [3]:
array2=array2.reshape(3,2)

In [4]:
array2[0][::-1]

array([2, 1])

In [5]:
array2[0,1]

2

In [6]:
array2[0][1]

2

In [7]:
ls=[1,2,3]
ls[1]=5
ls

[1, 5, 3]

In [8]:
array2[0,1]=5
array2[0]=0

In [9]:
array2[0]=1
array2

array([[1, 1],
       [3, 4],
       [5, 6]])

In [10]:
array2[1,1]

4

In [11]:
array2>8

array([[False, False],
       [False, False],
       [False, False]])

In [12]:
x=array2>1
array2[x]=100
array2

array([[  1,   1],
       [100, 100],
       [100, 100]])

In [13]:
array=np.array([[1,1,1],
       [2,2,2],
       [3,3,3]])
array

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [14]:
array>3
array>2
# array[]>1

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [25]:
x= array >2

In [26]:
array[x]

array([3, 3, 3])

In [29]:
array[x]=100
array

array([[  1,   1,   1],
       [  2,   2,   2],
       [100, 100, 100]])

In [38]:
a=np.zeros((2,3))
np.arange(5)


array([0, 1, 2, 3, 4])

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
a=1

In [46]:
type(a), array.dtype

(int, dtype('int64'))

In [48]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
array=np.array([[1,1,1],
       [2,2,2],
       [3,3,3]])
array

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [58]:
np.random.randint(100,130,size=(8,8))

array([[119, 102, 128, 126, 110, 126, 121, 122],
       [126, 101, 102, 101, 103, 126, 102, 104],
       [116, 116, 128, 111, 117, 114, 116, 114],
       [100, 110, 129, 101, 102, 108, 104, 120],
       [102, 117, 100, 102, 127, 117, 115, 102],
       [119, 108, 113, 124, 101, 111, 122, 115],
       [125, 110, 100, 129, 121, 127, 116, 106],
       [116, 110, 122, 119, 128, 126, 124, 108]])

In [3]:
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [9]:
datas=datas.astype(str)
datas[idx_3] = "fiz"
datas[idx_5] = "buzz"
datas[idx_3] = "fizzbuzz"
datas

array([['128', '127', '106', 'fizzbuzz', 'fizzbuzz', 'buzz', '103',
        '109'],
       ['107', '113', 'fizzbuzz', 'buzz', '113', 'buzz', 'fizzbuzz',
        '112'],
       ['118', 'fizzbuzz', 'fizzbuzz', 'fizzbuzz', 'buzz', '104',
        'fizzbuzz', 'fizzbuzz'],
       ['101', '127', '109', 'fizzbuzz', 'buzz', 'buzz', 'fizzbuzz',
        '124'],
       ['113', '107', '109', 'fizzbuzz', '106', 'fizzbuzz', 'fizzbuzz',
        '112'],
       ['fizzbuzz', 'fizzbuzz', 'fizzbuzz', '109', '113', 'fizzbuzz',
        'buzz', 'fizzbuzz'],
       ['104', 'fizzbuzz', '106', '106', 'fizzbuzz', '122', 'buzz',
        'fizzbuzz'],
       ['116', 'fizzbuzz', 'buzz', 'fizzbuzz', '112', 'buzz', 'fizzbuzz',
        'fizzbuzz']], dtype='<U21')

In [15]:
data= np.array(10 ,20 (5,5) )

TypeError: 'int' object is not callable

In [10]:
min_num, max_num = np.min(data),np.
idx_min = datas == min_num
idx_max = datas == max_num

NameError: name 'min_num' is not defined

In [11]:
def vectorinnerProd(x,y):
    return sum(x*y)

In [12]:
vectorinnerProd(a,b)

0

In [13]:
def vectorlength(x):
    return sum(x**2)**(1/2)

In [14]:
vectorlength(a)

1.4142135623730951

In [17]:
np.dot(a,a)**(1/2)

1.4142135623730951

In [19]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [22]:
B= np.array([[4,4],[2,1]])
B

array([[4, 4],
       [2, 1]])

<h1>linspace, logspace </h1>

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [21]:
#average salary in 30s $100000
#average salarty in 60s $1000000
age_30=100000
age_60=1000000

In [22]:
#increase of salary in linsapce
np.linspace(age_30,age_60,4)

array([ 100000.,  400000.,  700000., 1000000.])

In [26]:
#increase of salary in logspace
np.logspace(np.log10(age_30),np.log10(age_60),4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

<h1>Seed, rand, randn</h1>

<h3>seed produce random int values</h3>
<h3>rand produce random numbers in same interval  </h3>
<h3>randn produce random float type numbers by following standard distribution</h3> 
<h3>randint produce random int type numbers by following standard distribution</h3> 
<h3>suffle mixs matrix data</h3>
<h3>choice choose data with certain possibility</h3> 

In [30]:
np.random.seed(1)
result1 = np.random.randint(10,100,10)

np.random.seed(1)
result2 = np.random.randint(10,100,10)

np.random.seed(2)
result3 = np.random.randint(10,100,10)
result1,result2,result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [31]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [33]:
np.random.randn(10)

array([-0.33882197, -0.23618403, -0.63765501, -1.18761229, -1.42121723,
       -0.1534952 , -0.26905696,  2.23136679, -2.43476758,  0.1127265 ])

In [35]:
#shuffle
r = np.random.randint(1,10,(3,4))
r

array([[9, 6, 4, 1],
       [1, 3, 9, 9],
       [3, 7, 6, 7]])

In [37]:
np.random.shuffle(r)#shuffling the dimansion of  list data
r

array([[9, 6, 4, 1],
       [3, 7, 6, 7],
       [1, 3, 9, 9]])

In [38]:
#choice
np.random.choice(5, 10, p=[0.1,0,0.4,0.2,0.3] ) 


array([2, 4, 2, 0, 2, 0, 4, 4, 4, 3])

In [39]:
np.unique(r)

array([1, 3, 4, 6, 7, 9])

In [41]:
numbers,counts = np.unique(r,return_counts=True) #counts=return_counts=True, frequency of number produced
numbers, counts

(array([1, 3, 4, 6, 7, 9]), array([2, 2, 1, 2, 2, 3]))

<h1>merging data</h1>

In [44]:
na1=np.random.randint(10,size=(2,3))
na2=np.random.randint(10,size=(3,2))
na3=np.random.randint(10,size=(3,3))

In [47]:
na1,na2,na3

(array([[3, 0, 0],
        [5, 7, 5]]),
 array([[0, 8],
        [6, 5],
        [1, 7]]),
 array([[4, 3, 6],
        [1, 4, 0],
        [8, 5, 4]]))

In [49]:
np.concatenate((na1,na3))

array([[3, 0, 0],
       [5, 7, 5],
       [4, 3, 6],
       [1, 4, 0],
       [8, 5, 4]])

In [51]:
np.concatenate((na2,na3),axis=1)

array([[0, 8, 4, 3, 6],
       [6, 5, 1, 4, 0],
       [1, 7, 8, 5, 4]])

In [57]:
np.c_[np.array([[1,2,3],[2,3,4]]),np.array([[4,5,6],[5,2,3]])]#axis=0

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 2, 3]])

In [58]:
np.r_[np.array([[1,2,3],[2,3,4]]),np.array([[4,5,6],[5,2,3]])]#axis=1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6],
       [5, 2, 3]])

In [ ]:
###ipython 
-startup 파일 설정
    -주피터 노트북 실행시 미리 실행되는 코드 설정