In [1]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [2]:
array2= np.array(
    [[1,2,3],
    [4,5,6]]
)
array2,array2.ndim,array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [3]:
array2=array2.reshape(3,2)

In [4]:
array2[0][::-1]

array([2, 1])

In [5]:
array2[0,1]

2

In [6]:
array2[0][1]

2

In [7]:
ls=[1,2,3]
ls[1]=5
ls

[1, 5, 3]

In [8]:
array2[0,1]=5
array2[0]=0

In [9]:
array2[0]=1
array2

array([[1, 1],
       [3, 4],
       [5, 6]])

In [10]:
array2[1,1]

4

In [11]:
array2>8

array([[False, False],
       [False, False],
       [False, False]])

In [12]:
x=array2>1
array2[x]=100
array2

array([[  1,   1],
       [100, 100],
       [100, 100]])

In [13]:
array=np.array([[1,1,1],
       [2,2,2],
       [3,3,3]])
array

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [14]:
array>3
array>2
# array[]>1

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [25]:
x= array >2

In [26]:
array[x]

array([3, 3, 3])

In [29]:
array[x]=100
array

array([[  1,   1,   1],
       [  2,   2,   2],
       [100, 100, 100]])

In [38]:
a=np.zeros((2,3))
np.arange(5)


array([0, 1, 2, 3, 4])

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
a=1

In [43]:
type(a), array.

int